{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pluribusai.fullname" . }}
  labels:
    {{- include "pluribusai.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.token }}
  PLURIBUSAI_TOKEN: {{ .Values.auth.token | quote }}
  {{- else }}
  PLURIBUSAI_TOKEN: {{ randAlphaNum 32 | quote }}
  {{- end }}
  {{- if eq (include "pluribusai.useBundledPostgres" .) "true" }}
  POSTGRES_PASSWORD: {{ include "pluribusai.postgresPassword" . | quote }}
  {{- end }}
  {{- if eq (include "pluribusai.useExternalPostgres" .) "true" }}
  EXTERNAL_DB_PASSWORD: {{ include "pluribusai.postgresPassword" . | quote }}
  {{- end }}
  {{- if .Values.auth.apiKeys }}
  api-keys.json: |-
    {{ .Values.auth.apiKeys | toJson }}
  {{- end }}
  {{- if .Values.auth.jwtSecret }}
  PLURIBUSAI_JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  {{- end }}
  {{- if and .Values.auth.controlPlaneUrl .Values.auth.internalSecret }}
  PLURIBUSAI_INTERNAL_SECRET: {{ .Values.auth.internalSecret | quote }}
  {{- end }}
{{- end }}